name: Docker image build and push to public dockerhub 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch unshallow
      run: git fetch --prune --tags --unshallow
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.5
      with:
        versionSpec: '5.5.x'
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.5
    - run: |
        echo "Major: ${{ steps.gitversion.outputs.major }}"
        echo "Minor: ${{ steps.gitversion.outputs.minor }}"
        echo "Patch: ${{ steps.gitversion.outputs.patch }}"
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag mani0070/azdevopsbuildsbrowser:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push mani0070/azdevopsbuildsbrowser:${{steps.vars.outputs.tag}}
    - name: Build the Docker image latest tag
      run: docker build . --file Dockerfile --tag mani0070/azdevopsbuildsbrowser:latest
    - name: Push the latest Docker image
      run: docker push mani0070/azdevopsbuildsbrowser:latest
